#!/bin/sh
setxkbmap -layout "us,ru" -option caps:swapescape -option "grp:alt_shift_toggle, grp_led:scroll" -variant ",winkeys" -rules xorg -keycodes evdev
xrandr --output HDMI1 --mode 1920x1080 --output eDP1 --mode 1920x1080 --left-of HDMI1
exec $HOME/dwm-bar/dwm_bar.sh
sudo dhclient -r      
sleep 0.1
#sudo killall wpa_supplicant


